name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32e80e52aea5089c3e1a8b04f624dd8c1224f8cbcf3f629f253df44fbbbf532e"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
