name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "021f251d9aa15744692d33cf98e3122cbea6c01c627b9304f22a6f6116569bea"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
