name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cacac26a2516d4ddaf98a25ee337a227a1c658e445f2a4e108d40cbc0a17643c"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
