name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df0804d77753679c5dcfd0c9ec3ddf1167cc31cfe1bea175fcaa1c6b9fe09de"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
