name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f06e995008e5099ccda7fbc68191d08659967eae9431250ca6132e086263c145"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
