name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa6cf358b9556dadd987a0b8fee87ab95c5700f1396f288ea6980e14ce0609cb"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
