name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d93bfd58c763266a19d92075c904e3c2499a769fa4fadd7491b1b0d451a995"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
