name = "TMTD Private Pack"
author = "Yes"
version = "0.0.00.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7738c6e80f78c09466190f134267e9d55caedc4be17aa8ac444f7931185432a2"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
